CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR (255) NOT NULL,
    password VARCHAR (255) NOT NULL,
    email VARCHAR (255)
);

CREATE TABLE IF NOT EXISTS decks (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS cards (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    term VARCHAR (65535) NOT NULL,
    description VARCHAR (65535) NOT NULL
);

CREATE TABLE IF NOT EXISTS decklists (
    deck_id INTEGER NOT NULL,
    card_id INTEGER NOT NULL,
    FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE,
    FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS owners (
    user_id INTEGER NOT NULL,
    deck_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE
);